#!/bin/sh

cp $HOME/.local/share/konsole/default.profile src/konsole/default.profile
cp $HOME/.config/{kdeglobals,kglobalshortcutsrc,kxkbrc} src/plasma/
grep -v 'Latitude
Longitude' $HOME/.config/kwinrc > src/plasma/kwinrc
cp $HOME/.config/zsh/{.zshrc,.zprofile} src/zsh/

cp -r $HOME/.config/{git,mpv,nvim} src/
