#!/bin/sh

cp $HOME/.local/share/konsole/default.profile src/konsole/default.profile
cp $HOME/.config/{kdeglobals,kglobalshortcutsrc,kwinrc,kxkbrc} src/plasma/
cp $HOME/.mozilla/firefox/default/ src/firefox/

cp -r $HOME/.config/{zsh,git,mpv,nvim} src/
